### ISSUE TITLE
Unified Jacobian Protocol that can handle both complex and primitive types

### ISSUE THREAD

**Issue by ProfFan** [borglab/SwiftFusion#13]
I always find this quite annoying when implementing generic stuff related to `TangentVector`:

In JacobianProtocol you will find out that I am using different generics for `Double` and non-`Double` types, and I tried to make it more generic by introducing the `JacobianEvaluatable` protocol. However, the `basisVectors()` method only works for tangent types that is complex, so the current implementation will fail for tangents of `[Rot2]`, which is `[Double]`.

**Comment by dellaert** [comment]
Can you make the TangentType 1D vectors?

**Comment by ProfFan** [comment]
@dellaert Currently all the tangents are expressed as structs synthesized by the compiler, except Rot2 which is defined explicitly in the definition as `Double`. I will try `[Double]` and associated structs and report the results.

It would be very intuitive if we can express all the tangents in terms of vectors, but that is another issue-we currently do not have a working "small matrix" library in S4TF as far as I have investigated. Maybe @marcrasi have suggestions?

**Comment by marcrasi** [comment]
re "small matrix": How does https://developer.apple.com/documentation/accelerate/simd look to you? Unfortunately it only exists on macos. (Maybe it'll come to linux eventually, possibly with a different API? I've asked, I'll let you know if I get a response.) We could write a wrapper around it and provide a different implementation on linux, and then swap out the implementation if/when simd comes to linux. (I work mainly on linux and also Colab runs on linux, which is why I think it's important to support linux. I'd be happy to add linux implementations of anything that you use so that you don't have to figure out how to test things on linux.)

re the original question about `TangentVector` and `JacobianEvaluable`: Here's an idea:
```
protocol VectorSpace {
  var basisVectors: [Self] { get }
}

func jacobian<A: Differentiable, B: Differentiable>(...) where B.TangentVector: VectorSpace {
  ...
}

extension Double: VectorSpace {
  var basisVectors: [Self] { [1.0] }
}

extension KeyPathIterable {
  var basisVectors: [Self] { ... }
}
```
This fixes your problem. There is one drawback: you can't tell swift to automatically conform things to `VectorSpace` when they conform to `KeyPathIterable` (e.g. you can't do `extension KeyPathIterable: VectorSpace`), so your `TangentVector`s won't automatically get a conformance to `VectorSpace`. But it only takes one line per custom type to add the conformance. e.g.:
```
extension Rot2.TangentVector: VectorSpace {}
```

Let me know if you'd like me to send a PR fleshing out that idea. (Though if you want to try it out yourself, feel free to do that too!)

**Comment by dellaert** [comment]
Can't we use tensorflow math?

**Comment by marcrasi** [comment]
Yeah, tensorflow math would be a good way to start too, and I think it's probably the easiest thing to use in the short term. It already has a lot of linear algebra that we can use.

I would suggest wrapping all calls to it so that it's easy to swap it out when we have time to get something that works better. Wrapping would also allow you to have statically-ranked or statically-shaped types like `Vector`, `Matrix`, `Vector2`, `Matrix2x2`, etc, if that's something useful.

**Comment by ProfFan** [comment]
@marcrasi Thanks a lot! We are basically on the same track, though I never realized that we can use `extension` to get conformance 😄

**Comment by ProfFan** [comment]
Also, @marcrasi please feel free to add a PR, I tried to add the `extension`s but it was not working for me...

**Comment by marcrasi** [comment]
I discovered a bug in Swift AutoDiff while working on this: https://bugs.swift.org/browse/TF-1227. That may be why you were having trouble.

In the meantime, I figured out a workaround that is slightly more complicated but that seems okay. I'll send a PR for that.
