### ISSUE TITLE
Adjoint and adjoint

### ISSUE THREAD

**Issue by dellaert** [borglab/SwiftFusion#21]
So, referring to the [the wikipedia page](https://en.wikipedia.org/wiki/Adjoint_representation#Adjoint_representation_of_a_Lie_algebra) on this for a quick read, there are two operators, respectively associated with the Lie group and Lie algebra. For example, for SO(3), we have

1. Ad_R X = R X R^-1 where X is skew-symmetric matrix in so(3)
2. ad_X Y = [X,Y] where both X and Y are skew-symmetric matrices

I personally don't love the name "representation", as we typically use them more as *actions*. The fact that are representations for the group resp. algebra is of interest to mathematicians, and less to us. So, I'd prefer to call them the "Adjoint action (of the group)" and "adjoint action (of the algebra)", and so my proposal is:

1. name the first `groupAdjoint" 
2. name the second `adjoint"

Also, in GTSAM - and we decided to do the same here, we don't bother with the 3x3 elements of so(3) or se(3) but just use Vector3 instead. Hence, I propose that the type signatures are:

1. groupAdjoint: Rot3 -> (Vector3 -> Vector3), just implementing R*w (and not R \hat(w) R^T) 
1. adjoint: Vector3 -> (Vector3 -> Vector3), just implementing cross product :-)

Finally, there are the matrices associated with these actions:

1. groupAdjointMap: Rot3 -> Matrix3, just implementing R
1. adjointMap: Vector3 -> Matrix, just implementing skew-symmetric matrix

Of course, the examples above are for SO(3), but this would be analogous for all.

I am not yet in love with the solution, as I prefer "Adjoint" and "adjoint", if we can get away with flounting style. @marcrasi ?

**Comment by marcrasi** [comment]
Thanks for the explanation!

For API style, I try to follow https://swift.org/documentation/api-design-guidelines/. Under "Use Terminology Well" it does allow widely precedented terms in specific domains to outweigh other guidelines. However, `lowerCamelCase` for function names is a pretty strong guideline and I've never seen anything else violating it. So I'd prefer not having a method that starts with upper case.

In particular, I'm a bit worried that having "Adjoint"/"adjoint" would tempt us or others to also name other functions with upper case so that we can name their differential with lower case. This would lead to a lot of inconsistently cased functions. (Though this worry could be invalid if we really only do this for "Adjoint"/"adjoint".)

Your idea `groupAdjoint`/`adjoint` seems like a great solution to me. It follows the Swift case convention but also manages to capitalize "Adjoint" for the group action!

My one other comment is: Could `groupAdjointMap`/`adjointMap` be `groupAdjointMatrix`/`adjointMatrix` instead? To me, "map" means the abstract concept of a function without a representation in a particular basis. "Matrix" is the concrete representation of a linear function as a matrix in a particular basis.

**Comment by dellaert** [comment]
why was it misleading?

**Comment by ProfFan** [comment]
*only at first sight

**Comment by marcrasi** [comment]
> About Adjoint: now that I know it is approved for “widely precedented use” I would advocate once more for Adjoint. Pinky-swear to limit this violation to this case :-)

I'd be happy to have it this way if you think it really is justified by the widely precedented use and if you think it's the clearest way to write it.

**Comment by dellaert** [comment]
yay :-)

**Comment by ProfFan** [comment]
Closing (please reopen if you think this should not be closed :)
